### ISSUE TITLE
(node:3972) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Pages' of undefined

### ISSUE THREAD

**Issue by Masterxilo** [luochen1990/nodejs-easy-pdf-parser#1]
with the attached pdf

[das 1-mal-1 1x1 des anlegens brochure-1x1-anlegen-de.pdf](https://github.com/luochen1990/nodejs-easy-pdf-parser/files/7643973/das.1-mal-1.1x1.des.anlegens.brochure-1x1-anlegen-de.pdf)

```
sudo npm install -g easy-pdf-parser
pdf2text 'das 1-mal-1 1x1 des anlegens brochure-1x1-anlegen-de.pdf'
(node:299) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Pages' of undefined
    at extractText (/usr/lib/node_modules/easy-pdf-parser/src/easy-pdf-parser.js:22:38)
    at extractPlainText (/usr/lib/node_modules/easy-pdf-parser/src/easy-pdf-parser.js:43:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

another program can read it just fine, e.g.

```
pdftotext 'das 1-mal-1 1x1 des anlegens brochure-1x1-anlegen-de.pdf' -
```

**Comment by Masterxilo** [comment]
see https://stackoverflow.com/questions/7719499/print-contents-of-a-pdf-to-the-command-line/51337079?noredirect=1#comment124056295_51337079

**Comment by luochen1990** [comment]
I can run this successfully.

```
$ node --version  
v10.19.0
```

and the tail of this pdf document's text content is

```
----- page 31 -----

22803_Broschuere_1x1Anleger_d_2015_08_19.indd   2 21.12.15   16:57 22803_Broschuere_1x1Anleger_d_2015_08_19.indd   31 21.12.15   16:57

----- page 32 -----

Diese Publikation dient nur zur Information. Sie ist weder als 
Empfehlung, Offerte oder Aufforderung zur Offertstellung 
noch als Rechts- oder Steuerberatung zu verstehen. Sie sollten 
sich professionell beraten lassen, bevor Sie eine Entscheidung 
treffen. UBS behält sich das Recht vor, Dienstleistungen, 
Produkte und Preise jederzeit ohne Vorankündigung zu ändern. 
Einzelne Dienstleistungen und Produkte unterliegen rechtli-
chen Restriktionen. Sie können deshalb nicht uneingeschränkt 
weltweit angeboten werden. Die vollständige oder teilweise 
Reproduktion ohne ausdrückliche Erlaubnis von UBS ist untersagt. 
UBS Switzerland AG
Postfach
8098 Zürich
© UBS 2020. Das Schlüsselsymbol und UBS gehören zu den geschützten Marken von UBS. Alle Rechte vorbehalten. August 2020. 84219D

```

I don't know why it doesn't work for you yet...

**Comment by Masterxilo** [comment]
I see @luochen1990 . I have a different node version

```
$ node --version
v14.16.0
$ npm --version
6.14.11
```

**Comment by luochen1990** [comment]
That is weird, from your stacktrace info, it seems that there is no `Pages` attribute [here](https://github.com/luochen1990/nodejs-easy-pdf-parser/blob/master/src/easy-pdf-parser.js#L22), and this seems impossible to be a nodejs version compatibility issue... hmmm

**Comment by Robak08** [comment]
@luochen1990 I'm running into similar problem, seems to be after pdf2json dependency minor version update to above 1.2.3 (1.3.1atm).

I believe it's connected with https://github.com/modesty/pdf2json/issues/249#issuecomment-953029255

data structure
```
//before
pdfData.formImage.Pages
//after
pdfData.Pages
```

biggest issue is that certain small svg elements aren't visible anymore in Fills Array for Pages Object. Those were present with version 0.0.4.

//edit

I've been also testing different pdf2json versions with node v14.16.0 and v16.14.2.  Few observations:

pdf2json v1.2.1 - v1.2.4:
- node v14.16.0, working with formImage.Pages structure
- node 16.14.2, silenty closing -> not parsing

pdf2json v1.3.1 and v2.0.1:
 - works with both node versions  but structure is lacking formImage
